development:
  password: 97272b3a3c63ef9c8a45b7d79c9bd514
  theme_id: 547586073
  store: verbalplusvisual.myshopify.com
  ignore_files:
    - settings_data.json

production: 
  password: 97272b3a3c63ef9c8a45b7d79c9bd514 
  theme_id: "live"
  store: verbalplusvisual.myshopify.com
  ignore_files:
    - settings_data.json